### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by kinshukgoel4** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#135]
Hey i believe i can work on this can you assign this to me.

**Comment by kinshukgoel4** [comment]
Generally, binary search works only on sorted lists/arrays but I have a piece of code which works even on un-sorted lists just how a binary search works with little more conditional statements. Hence assign me on this topic.

**Comment by fms12** [comment]
yes,

**Comment by kinshukgoel4** [comment]
Ok I will work on it can u please add hacktoberfest and hacktoberfest-accepted tag for this issue

**Comment by VARUNvk1729** [comment]
sure I'll add try to add comments along with code!!

**Comment by thechangamunda** [comment]
The issue is still open, can I work on this ?

**Comment by kinshukgoel4** [comment]
Hey @VARUNvk1729 @fms12  I have submitted a PR for this issue please checkout and update me.  Thanks
