### ISSUE TITLE
Tests should be added

### ISSUE THREAD

**Issue by devvspaces** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#136]
There should be test cases that verify that the provided solutions are working

the way this may be done is this

```
- questions
   - question1
      - solution.py
      - test_solution.py
```

**Comment by devvspaces** [comment]
file structure should be re-organized too, so that people can easily find solutions. I saw two separate codes for implementing binary search

**Comment by devvspaces** [comment]
Comments might be added to code to make it more clear, write out the question at the top of the solution using multiline strings i suggest.

I want to add a LinkedList implementation (Singly and Doubly) + tests too.

**Comment by fms12** [comment]
> There should be test cases that verify that the provided solutions are working
> 
> the way this may be done is this
> 
> ```
> - questions
>    - question1
>       - solution.py
>       - test_solution.py
> ```
thank you for pointing out these things. can you do all of this

**Comment by devvspaces** [comment]
yes, already on it, will create a PR soon

**Comment by devvspaces** [comment]
but i

> > There should be test cases that verify that the provided solutions are working
> > the way this may be done is this
> > ```
> > - questions
> >    - question1
> >       - solution.py
> >       - test_solution.py
> > ```
> 
> thank you for pointing out these things. can you do all of this

i have added it already, you can review and check it
