### ISSUE TITLE
File organizing

### ISSUE THREAD

**Issue by fms12** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#137]
add the proper structure to the file and folder.

**Comment by devvspaces** [comment]
hi, i would love to do this, as you can see some files are causing flake8 to fail

**Comment by fms12** [comment]
yaa, Thank you for pointing that out.

**Comment by fms12** [comment]
and we can start a discussion on this.

**Comment by devvspaces** [comment]
HI, this is completed.
