### ISSUE TITLE
add Flake8 to lint code

### ISSUE THREAD

**Issue by fms12** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#141]
add flake8 action in the workflow folder 

you can find it here:

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

**Comment by devvspaces** [comment]
added flake8 already in the workflow @fms12

**Comment by devvspaces** [comment]
but the tests is failing because there is a lot of errors in most files

**Comment by devvspaces** [comment]
I would clean all the files today, it will be a lot of work 😎

**Comment by fms12** [comment]
@devvspaces  thank you for your contribution 🙌
