### ISSUE TITLE
Valid Anagram

### ISSUE THREAD

**Issue by MiTo0o** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#15]
- Algorithm to check if strings are anagrams of each other

**Comment by fms12** [comment]
try to add it inside the string folder in the repo

**Comment by MiTo0o** [comment]
I just check, I think it's already in the String folder.

**Comment by fms12** [comment]
no its not

**Comment by MiTo0o** [comment]
hummm thats weird
its showing that it's in the string folder on my end

![image](https://user-images.githubusercontent.com/76019114/193443204-40c67032-e923-4e7c-a32d-4da12cef9c80.png)
![image](https://user-images.githubusercontent.com/76019114/193443222-6f5b33c9-36f8-4e0c-8de6-8375aff58775.png)
