### ISSUE TITLE
STACK

### ISSUE THREAD

**Issue by kinshukgoel4** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#169]

**Comment by kinshukgoel4** [comment]
HEY I CAN WORK ON THIS ISSUE @VARUNvk1729 @fms12 CAN YOU ASSIGN ME THIS TASK

**Comment by kinshukgoel4** [comment]
do add the hactoberfest and hactoberfest-accepted tags

**Comment by fms12** [comment]
ok, just mention the question here.

**Comment by kinshukgoel4** [comment]
Stack implementation using a linked list is the question. I can add it in Linked List folder if you want so.

**Comment by kinshukgoel4** [comment]
I will create a separate folder for Stack data structure and add it in this repo. It will include 3 questions:
1. Stack implementation in python using Lists
2. Stack implementation using Linked lists
3. Stack implementation using Queues.
Do add the hacktoberfest tags. Thank you in advance.

**Comment by VARUNvk1729** [comment]
Create stack folder and implement
