### ISSUE TITLE
SORTING

### ISSUE THREAD

**Issue by kinshukgoel4** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#170]

**Comment by kinshukgoel4** [comment]
HEY, I CAN ADD MORE TYPES OF OTHER SORTS EXCEPT FOR THE ONES WHICH ARE PRESENT IN THE SORTING FOLDER. PLEASE ASSIGN ME THIS TASK @VARUNvk1729 @fms12 AND DO ADD THE HACTOBERFEST TAGS

**Comment by fms12** [comment]
ok, just mention the questions here. which you are working on it

**Comment by kinshukgoel4** [comment]
I can work on Tim Sort and Bucket Sort. Add the hacktoberfest tags

**Comment by VARUNvk1729** [comment]
Go ahead

**Comment by kinshukgoel4** [comment]
@VARUNvk1729  I have made a PR on Tim Sort please check it out

**Comment by kinshukgoel4** [comment]
do add the hactoberfest-accepted tag to this issue and while merging my PR

**Comment by kinshukgoel4** [comment]
@VARUNvk1729 I have made a PR on Tim Sort please check it out and do add the hactoberfest-accepted tag to this issue and while merging my PR

**Comment by VARUNvk1729** [comment]
sure @kinshukgoel4 !!

**Comment by VARUNvk1729** [comment]
done @kinshukgoel4 !!
good job.

**Comment by kinshukgoel4** [comment]
Thanks, @VARUNvk1729 . It has been great contributing to this repo.

**Comment by VARUNvk1729** [comment]
It means a lot!!
keep sharing this repo to your friends too..

**Comment by kinshukgoel4** [comment]
Sure
