### ISSUE TITLE
add more algorithm in searching and sorting 

### ISSUE THREAD

**Issue by fms12** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#2]
### list of searching and sorting algorithm

**Marked Complete. when you did**

- [x] Binary Search
- [x] Liner Search
- [x] Insertion Sort
- [x] Bubble Sort
- [x] selection sort
- [x] quick sort
- [x] merge sort
- [x] count sort
- [x] heap sort
- [x] Radix sort
- [x] shell sort
- [x] Pigeonholesort.py

**Comment by Souvik-Nayak** [comment]
can i work on this issue ?

**Comment by Siddharthqr** [comment]
Please assign me this issue

**Comment by URRG** [comment]
can i pls contribute to this issue

**Comment by fms12** [comment]
@Souvik-Nayak  marked which you done

**Comment by Souvik-Nayak** [comment]
> ### list of searching and sorting algorithm
> **Marked Complete. when you did**
> 
> * []  Binary Search
> * [ ]  Liner Search
> * [ ]  Insertion Sort
> * [ ]  Bubble Sort
> * [x]  selection sort
> * []  quick sort
> * [ ]  merge sort
> * [ ]  count sort
> * [ ]  heap sort
> * [ ]  Radix sort
> * [ ]  shell sort

**Comment by sambhavgupta0705** [comment]
Hey I also want to contribute to it ,please assign it to me

**Comment by fms12** [comment]
> Hey I also want to contribute to it ,please assign it to me

Yes sure 👍

**Comment by sambhavgupta0705** [comment]
> ### list of searching and sorting algorithm
> **Marked Complete. when you did**
> 
> * [x]  Binary Search
> * [x]  Liner Search
> * [x]  Insertion Sort
> * [x]  Bubble Sort
> * [x]  selection sort
> * [x]  quick sort
> * [x]  merge sort
> * [ ]  count sort
> * [ ]  heap sort
> * [ ]  Radix sort
> * [ ]  shell sort

**Comment by sambhavgupta0705** [comment]
I have done bubble sort algorithm

**Comment by lognoroy** [comment]
Hey I also want to contribute to it ,please assign it to me

**Comment by achiverram28** [comment]
I want to contribute , I can satisfy all the algorithms of the list , please assign me this

**Comment by fms12** [comment]
someone would like to add the radix sort algorithm then we can close this issue?
