### ISSUE TITLE
Binary Search Tree

### ISSUE THREAD

**Issue by im45145v** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#209]
Can i add this ?
if so i'll write a program for that

**Comment by fms12** [comment]
sure!

**Comment by Kd-Here** [comment]
Is the work completed or should I try?

**Comment by fms12** [comment]
no, it's not completed. you can try it out

**Comment by Kd-Here** [comment]
Hey @fms12 I research and found a Bst code in python but needed some edit.
I can do that. Should I use someone's code here. It's from Programmiz website!

**Comment by fms12** [comment]
yes,
