### ISSUE TITLE
(PTC-W0068) Consider using identity comparison with singleton

### ISSUE THREAD

**Issue by fms12** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#25]
## Description
Comparisons to the singleton objects, like `True`, `False`, and `None`, should be done with identity, not equality. Use `is` or `is not`.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY/issue/PTC-W0068/occurrences/](https://deepsource.io/gh/fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY/issue/PTC-W0068/occurrences/)

**Comment by achiverram28** [comment]
I will do this

**Comment by achiverram28** [comment]
I have completed can you please check
