### ISSUE TITLE
(PYL-R1714) Consider using `in`

### ISSUE THREAD

**Issue by fms12** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#26]
## Description
To check if a variable is equal to one of many values, combine the values into a tuple and check if the variable is contained `in` it instead of checking for equality against each of the values. This is faster, less verbose, and more readable.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY/issue/PYL-R1714/occurrences/](https://deepsource.io/gh/fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY/issue/PYL-R1714/occurrences/)

**Comment by achiverram28** [comment]
I can resolve this

**Comment by fms12** [comment]
ok 👍

**Comment by achiverram28** [comment]
I have resolved it , can u check it, and merge the pull request
