### ISSUE TITLE
contributing.md file missing

### ISSUE THREAD

**Issue by nileshlad09** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#3]
According to hacktoberfest guidelines a contributing.md file should be there for projects which are participating in hacktoberfest.
Please assign this issue to me...

**Comment by fms12** [comment]
Ok , nilesh..

**Comment by nileshlad09** [comment]
can you please assign this to me under hacktoberfest

**Comment by fms12** [comment]
ok sure ,
