### ISSUE TITLE
Number pattern program

### ISSUE THREAD

**Issue by Baba-Yaga-1** [fms12/DATA-STRUCTURE-AND-ALGORITHM-IN-PY#32]
Can you assign me this issue?

**Comment by fms12** [comment]
sure 👍

**Comment by Baba-Yaga-1** [comment]
@fms12 Do I need to add 1 or more than 1 program related to the alphabet pattern ?

**Comment by fms12** [comment]
Do you want to add a number pattern or an alphabet pattern?

**Comment by Baba-Yaga-1** [comment]
> Do you want to add a number pattern or an alphabet pattern?

Yeah actually Number pattern .
By mistake I wrote alphabet .

**Comment by fms12** [comment]
ok, add it to the pattern folder as Patter "serial no" with proper comments
